from abc import ABC, abstractmethod
import random
import math
from typing import List
import logging

import spacy
import matplotlib.pyplot as plt
import numpy as np
from model.engine import LLMAdapter
from adapters.WikiKnowledgeGraph import KnowledgeGraph
from adapters.OAI_Embeddings import EmbedAdapter
from similarity.cosine_similarity import similarity

class SemanticPerturber(ABC):
    @abstractmethod
    def sem_perturb(self, user_prompt):
        """
        Apply a semantic perturbation to the input prompt.

        Args:
            user_prompt (str): The input text prompt to be perturbed.

        Returns:
            str: The semantically perturbed version of the input prompt.
        """
        pass
    
    @abstractmethod
    def setup_for_tree(self, prompt):
        pass
    
    @abstractmethod
    def post_process(self):
        pass

class ParaphrasePerturber(SemanticPerturber):
    def __init__(self, model):
        self.model:LLMAdapter=model


    def setup_for_tree(self, prompt):
        pass
    
    
    def sem_perturb(self, user_prompt, prompt_list=None, temp=0):
        forbid_text = ""
        instruction = (
            "Generate a variation of the following user prompt "
            "by perturbing its semantics while preserving its core intent. "
            "Return just the string of the perturbed prompt."
        )
        
        if prompt_list is not None:
            forbid_text = "\n".join([f"{idx}. {p}" for idx, p in enumerate(prompt_list, start=1)])
            instruction += (
                "\nHowever, there are several sentence variations generated by "
                "others that you MUST NOT repeat since we want new variations.\n"
                f"Sentences are in this list:\n{forbid_text}"
            )

        prompt = self.model.format_prompt(
            user_prompt,
            state=[{
                "role": "system",
                "content": instruction
            }]
        )

        response, _ = self.model.complete(prompt, temperature=temp)
        return response
    
    
    def post_process(self):
        pass


class PrefixPerturber(SemanticPerturber):
    def __init__(self, embdder, tree_size):
        # resets at every tree
        self.knowledge_graph = None
        self.root_embeddings = None
        
        # constant
        self.embedder: EmbedAdapter = embdder
        self.k_hop = tree_size[0] + 1
        self.top_k = tree_size[1] + 1
        self.NER = spacy.load(
            "en_core_web_trf"
        )
    
        
    def setup_for_tree(self, prompt):
        entity_list = self.NER(prompt)
        root_entity = [li.text for li in list(entity_list.ents)][0] 
        # create new knowledge graph instance
        self.knowledge_graph = KnowledgeGraph(
            root_entity,
            k_hop=self.k_hop,
            top_k=self.top_k,
            prompt=prompt,
            embedder=self.embedder,
        )
        root_passages = [child.content for child in self.knowledge_graph.graph.children]
        self.root_embeddings = [self.embedder.encode(rp) for rp in root_passages]

    def sem_perturb(self, user_prompt, K=30, T_init=1.0, T_decay=0.9, return_sim=False, prompt_list=None, temp=0):
        """
        Perturbs the prompt by swapping its prefix with a candidate document fetched from the knowledge graph.
        The objective is to minimize the average similarity between the prompt embedding and the provided root embeddings.
        """
        # Score function: lower average similarity (more negative) is better.
        def score_fn(prompt):
            emb = self.embedder.encode(prompt)
            sims = [similarity(root_emb, emb) for root_emb in self.root_embeddings]
            return -np.mean(sims)

        node_visited = set()
        # Keep the original prompt separate.
        base_prompt = user_prompt
        current_prefix = ""  # start with no prefix
        current_prompt = f"{current_prefix} {base_prompt}".strip()
        current_score = score_fn(current_prompt)
        best_prefix = current_prefix
        best_score = current_score

        # Track the last candidate seen
        last_candidate = None

        T = T_init

        for iteration in range(K):
            # Retrieve candidate document from the knowledge graph.
            kg_context, kg_title, kg_content, kg_idx = self.knowledge_graph.get_next_document()
            # Instead of appending, we swap the prefix.
            candidate_prefix = kg_context.strip()
            last_candidate = candidate_prefix  # update last candidate seen
            if candidate_prefix in node_visited:
                continue
            node_visited.add(candidate_prefix)
            new_prompt = f"{candidate_prefix} {base_prompt}"
            new_score = score_fn(new_prompt)

            # Acceptance probability via simulated annealing.
            delta = new_score - current_score
            p_accept = min(1, math.exp(math.exp(delta / T)))

            if random.random() < p_accept:
                current_prefix = candidate_prefix  # swap prefix
                current_prompt = new_prompt
                current_score = new_score

                # Update best if improved.
                if current_score > best_score:
                    best_score = current_score
                    best_prefix = current_prefix

            T *= T_decay  # decay the temperature

        # If best_prefix is empty or whitespace, use the last seen candidate (if it's not empty)
        if not best_prefix.strip() and last_candidate is not None and last_candidate.strip():
            best_prefix = last_candidate

        self.knowledge_graph.update_visit_status(best_prefix)
        best_prompt = f"{best_prefix} {base_prompt}".strip()
        best_similarity = -best_score  # convert back to similarity

        if return_sim:
            return best_prompt, best_similarity
        else:
            return best_prompt

    def post_process(self):
    # Save the boolean array of ordered docs visited as a heatmap image.
    # The heatmap is saved with the knowledge graph's root entity as the filename.
        if self.knowledge_graph is not None:
            # Retrieve the visited flags from the knowledge graph.
            visited_flags = self.knowledge_graph._visited_doc_flags
            # Convert to a NumPy array and reshape it into a 2D array (a single row).
            heatmap_data = np.array(visited_flags, dtype=int).reshape(1, -1)
            
            plt.figure(figsize=(10, 2))
            # Display the heatmap. For a boolean array, using a colormap like 'viridis' can help highlight visited (1) vs. not visited (0).
            plt.imshow(heatmap_data, cmap='viridis', aspect='auto')
            plt.colorbar(label='Visited (1=True, 0=False)')
            plt.title('Knowledge Graph Document Visitation')
            plt.xlabel('Document Index')
            plt.yticks([])  # Hide the y-axis ticks since it's a single row
            
            # Determine the filename based on the knowledge graph's root entity.
            if hasattr(self.knowledge_graph.graph, 'title'):
                filename = f"{self.knowledge_graph.graph.title}_heatmap.png"
            else:
                filename = "knowledge_graph_heatmap.png"
                
            plt.savefig(filename)
            plt.close()
            print(f"Heatmap saved as {filename}")

        # Clean up resources.
        if self.knowledge_graph is not None:
            del self.knowledge_graph
        if self.root_embeddings is not None:
            del self.root_embeddings
            
            