from model.engine import LLMAdapter
from typing import List
import re
import logging
import random
import json
import logging
import time

class SemanticAdapter:
    def __init__(self, model):
        self.model:LLMAdapter=model
        self.MAX_RETRY=5
        pass

    def wiki_rag_completions(self, model_name, system_prompt, user_prompt):
        prompt=self.model.format_prompt(
            user_prompt,
            state=[{
                    "role": "system",
                    "content": system_prompt,
                }]
            )
        response, _ = self.model.complete(prompt)
        return response
    
    
    def sem_perturb(self, user_prompt, prompt_list=None, temp=0):
        forbid_text = ""           
        insruction = ("Generate a variation of the following user prompt "
                        "by perturbing its semantics while preserving its core intent. "
                        "Return just the string of the perturbed prompt.")
        if prompt_list is not None:
            forbid_text = "\n".join([f"{idx}. {p}" for idx, p in enumerate(prompt_list, start=1)])
            insruction += ("However, there are several sentences variations generated by "
                           "others that you MUST NOT repeat since we want new variations."
                            f"Sentences are in this list:\n{forbid_text}")
        prompt=self.model.format_prompt(
            user_prompt,
            state=[{
                    "role": "system",
                    "content": insruction
                }]
            )

        response, _ = self.model.complete(prompt, temperature=temp)
        return response
    
    def sem_check(self, question_prompt, model_name):
        prompt=self.model.format_prompt(
        question_prompt,
        state=[{
                "role": "system",
                "content": ("You are a helpful assistant who is supposed to answer questions given to you. " 
                "Keep the answers as concise as possible, does not have to be full sentences.")
            }]
        )
        response, _ = self.model.complete(prompt)
        return response